# Generated by Django 2.0.7 on 2018-08-03 05:01

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('backend', '0005_auto_20180803_0855'),
    # ]

    operations = [
        migrations.CreateModel(
            name='UpcomingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=backend.models.upload_image_path)),
                ('created_date', models.DateField(verbose_name='Added Date')),
                ('updated_date', models.DateField(verbose_name='Updated Date')),
                ('launched_date', models.DateField(verbose_name='Launched Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
